# Generated by Django 5.0.6 on 2024-06-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RopaScraping',
        ),
    ]
