# Generated by Django 5.0.6 on 2024-06-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraping', '0002_delete_ropascraping'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPrendasScraping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=40, null=True)),
                ('talla', models.CharField(blank=True, max_length=5, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_ropa', models.CharField(blank=True, max_length=20, null=True)),
                ('categoria', models.CharField(blank=True, max_length=30, null=True)),
                ('img', models.CharField(blank=True, max_length=225, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
