# Generated by Django 5.0.6 on 2024-06-17 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoprendasscraping',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='infoprendasscraping',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='infoprendasscraping',
            name='tipo_ropa',
        ),
    ]
