# Generated by Django 5.0.6 on 2024-07-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_remove_infoprendasscraping_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoprendasscraping',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.RenameField(
            model_name='infoprendasscraping',
            old_name='img',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='infoprendasscraping',
            old_name='precio',
            new_name='precio_normal',
        ),
        migrations.RemoveField(
            model_name='infoprendasscraping',
            name='talla',
        ),
        migrations.AddField(
            model_name='infoprendasscraping',
            name='precio_oferta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
