# Generated by Django 5.0.6 on 2024-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_rename_fecha_infoprendasscraping_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoprendasscraping',
            name='precio_normal',
            field=models.CharField(default='0.00', max_length=10),
        ),
        migrations.AlterField(
            model_name='infoprendasscraping',
            name='precio_oferta',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
