# Generated by Django 5.0.6 on 2024-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0006_alter_infoprendasscraping_precio_normal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoprendasscraping',
            name='imagen',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
