# Generated by Django 5.0.6 on 2024-05-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_alter_categoria_descripcion'),
        ('estante', '0001_initial'),
        ('productos', '0003_alter_producto_descripcion'),
        ('proveedor', '0003_alter_proveedor_correo_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_estante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estante.estante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
