# Generated by Django 5.0.6 on 2024-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_id_categoria_producto_id_estante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='img',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
