# Generated by Django 5.0.6 on 2024-06-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_id_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
