# Generated by Django 5.0.6 on 2024-06-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_id_categoria_producto_id_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
