# Generated by Django 5.0.6 on 2024-06-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
        ('productos', '0014_alter_producto_id_estante_and_more'),
        ('subcategoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_estante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estante.estante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategoria.subcategoria'),
        ),
    ]
