# Generated by Django 5.0.6 on 2024-06-10 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_id_estante_and_more'),
        ('proveedor', '0003_alter_proveedor_correo_alter_proveedor_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedor.proveedor'),
        ),
    ]
