# Generated by Django 5.0.6 on 2024-07-09 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0017_alter_producto_id_subcategoria'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_estante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.estante'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.subcategoria'),
        ),
    ]
