# Generated by Django 5.0.6 on 2024-07-30 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
        ('productos', '0020_alter_producto_id_subcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_estante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estante.estante'),
        ),
    ]
