# Generated by Django 5.0.6 on 2024-07-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_estante'),
        ('productos', '0022_alter_producto_id_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_estante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.estante'),
        ),
    ]
