# Generated by Django 5.0.6 on 2024-07-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobante', '0001_initial'),
        ('pedido', '0002_alter_pedido_id_cliente'),
        ('tipo_comprobante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='id_pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.pedido'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='id_tipo_comprobante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_comprobante.tipocomprobante'),
        ),
    ]
