# Generated by Django 5.0.6 on 2024-05-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, null=True)),
                ('apellido', models.CharField(max_length=60, null=True)),
                ('documento', models.CharField(max_length=8, null=True)),
                ('fecha_nacimiento', models.DateTimeField(null=True)),
                ('sexo', models.CharField(max_length=10, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('id_metodo_pago', models.IntegerField(null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('contraseña', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
