# Generated by Django 5.0.6 on 2024-05-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
