# Generated by Django 5.0.6 on 2024-06-21 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0018_alter_cliente_id_metodo_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='clientes.cliente')),
            ],
        ),
    ]
