# Generated by Django 5.0.6 on 2024-06-21 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0019_clientetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientetoken',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
