# Generated by Django 5.0.6 on 2024-05-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
