# Generated by Django 5.0.6 on 2024-05-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('estado', models.IntegerField(default=0)),
            ],
        ),
    ]
