# Generated by Django 5.0.6 on 2024-05-27 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_rename_ubicacion_inventario_numero_almacen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='numero_almacen',
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
