# Generated by Django 5.0.6 on 2024-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_inventario_numero_almacen_inventario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
