# Generated by Django 5.0.6 on 2024-07-30 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_inventario_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id_estante', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estante', models.IntegerField()),
                ('id_inventario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario')),
            ],
        ),
    ]
