# Generated by Django 5.0.6 on 2024-05-31 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        ('clientes', '0014_alter_cliente_id_metodo_pago'),
        ('productos', '0004_producto_id_categoria_producto_id_estante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=120)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=1)),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.administrador')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
