# Generated by Django 5.0.6 on 2024-07-30 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
        ('productos', '0022_alter_producto_id_proveedor'),
        ('reembolso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reembolso',
            name='id_administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrador.administrador'),
        ),
        migrations.AlterField(
            model_name='reembolso',
            name='id_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
