# Generated by Django 5.0.6 on 2024-05-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(default='Nueva Categoria', max_length=30),
        ),
    ]
