# Generated by Django 5.0.6 on 2024-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='documento',
            new_name='numero_ruc',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='telefono',
            new_name='telefono_principal',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='usuario',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
