# Generated by Django 5.0.6 on 2024-05-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_rename_documento_proveedor_numero_ruc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='numero_ruc',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='representante',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_principal',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono_secundario',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
