# Generated by Django 5.0.6 on 2024-05-27 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_rename_ubicacion_inventario_numero_almacen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id_estante', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estante', models.IntegerField()),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
            ],
        ),
    ]
