# Generated by Django 5.0.6 on 2024-07-30 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
        ('inventario', '0004_alter_inventario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estante',
            name='id_inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.inventario'),
        ),
    ]
